---
- hosts: all

  tasks:
    - name: Creates directory
      file: path=/src/minecraft state=directory

    - git_config:
        name: user.email
        repo: /etc
        scope: local
        value: 'minecraft@{{ ansible_fqdn }}'

    - name: Download repository locally
      git:
        repo: "{{ lookup('env','REPO') }}"
        dest: /src/minecraft
        clone: yes

    - name: Create minecraft container
      docker_container:
        name: minecraft
        image: itzg/minecraft-server
        state: present
        ports:
        - "25565:25565"
        env:
          EULA: TRUE
        volumes:
          - "/src/minecraft:/data"